# Generated by Django 4.0 on 2024-05-11 08:29

from django.db import migrations, models
import django.db.models.deletion
import toprofile_api.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to=toprofile_api.models.AboutUs.upload_to)),
                ('about', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(null=True)),
                ('body', models.TextField()),
                ('status', models.CharField(choices=[('published', 'Published'), ('draft', 'Draft')], default='published', max_length=10)),
                ('image', models.ImageField(null=True, upload_to=toprofile_api.models.Blog.upload_to)),
                ('read_min', models.CharField(max_length=300, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_image', models.ImageField(null=True, upload_to=toprofile_api.models.HomePage.upload_to)),
                ('title', models.TextField()),
                ('content', models.TextField(null=True)),
                ('location', models.CharField(max_length=500, null=True)),
                ('phone_number', models.TextField(null=True)),
                ('email_link', models.URLField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ListingCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OurServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to=toprofile_api.models.OurServices.upload_to)),
                ('title', models.CharField(max_length=500)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='OurTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to=toprofile_api.models.OurTeam.upload_to)),
                ('name', models.TextField(null=True)),
                ('title', models.CharField(max_length=500)),
                ('facebook_link', models.URLField()),
                ('instagram_link', models.URLField()),
                ('email_link', models.URLField()),
                ('twitter_link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='PrivatePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Statement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TermsOfService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PropertyListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('content', models.TextField()),
                ('place', models.CharField(max_length=500, null=True)),
                ('address', models.CharField(max_length=500, null=True)),
                ('status', models.CharField(choices=[('published', 'Published'), ('draft', 'Draft')], default='published', max_length=10)),
                ('duration', models.IntegerField(default=0)),
                ('land_space', models.IntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=0, max_digits=10)),
                ('no_bedroom', models.IntegerField(default=0)),
                ('no_bathroom', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='toprofile_api.listingcategory')),
            ],
        ),
        migrations.CreateModel(
            name='ImageAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=toprofile_api.models.ImageAsset.upload_to)),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='toprofile_api.propertylisting')),
            ],
        ),
    ]
