# Generated by Django 4.0 on 2024-05-12 08:08

from django.db import migrations, models
import toprofile_api.models


class Migration(migrations.Migration):

    dependencies = [
        ('toprofile_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to=toprofile_api.models.Agent.upload_to)),
                ('name', models.TextField(null=True)),
                ('title', models.CharField(max_length=500)),
                ('facebook_link', models.URLField()),
                ('instagram_link', models.URLField()),
                ('email_link', models.URLField()),
                ('twitter_link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='FillContactForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Testimony',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('comment', models.TextField()),
                ('status', models.CharField(choices=[('published', 'Published'), ('draft', 'Draft')], default='draft', max_length=10)),
                ('image', models.ImageField(null=True, upload_to=toprofile_api.models.Testimony.upload_to)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
